name: Mycodo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [debian-bullseye, debian-bookworm]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Workaround for https://github.com/actions/runner-images/issues/675  
        run: |
          # Only required for Debian based OS (Bullseye, Bookworm)
          if [[ ${{ runner.os }} == 'Linux' ]]; then
            sudo gem install apt-spy2
            sudo apt-spy2 fix --commit --launchpad --country=US
          fi
      - name: Install dependencies
        run: |
          # Update and install base dependencies
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
          
          # Configure package sources based on OS
          if [[ ${{ runner.os }} == 'ubuntu-latest' ]]; then
            # Ubuntu
            sudo add-apt-repository universe
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          else
            # Debian (Bullseye, Bookworm)
            sudo echo "deb http://deb.debian.org/debian ${{ matrix.os }} main contrib non-free" | sudo tee /etc/apt/sources.list
            sudo echo "deb-src http://deb.debian.org/debian ${{ matrix.os }} main contrib non-free" | sudo tee /etc/apt/sources.list.d/source.list
          fi
          
          # Update and install remaining dependencies
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt install -y libatlas-base-dev libboost-python-dev gawk git libffi-dev libi2c-dev nginx python3-dev sqlite3 swig
          sudo bash mycodo/scripts/upgrade_commands.sh update-packages
          git clone --recursive https://github.com/WiringPi/WiringPi-Python.git && cd WiringPi-Python && git submodule update --init && cd WiringPi && ./build && cd ../..
          sudo bash mycodo/scripts/upgrade_commands.sh build-pigpiod
          sudo bash mycodo/scripts/upgrade_commands.sh update-influxdb-1
          sudo service influxdb start && sleep 3
          sudo bash mycodo/scripts/upgrade_commands.sh update-influxdb-1-db-user
          sudo useradd -M mycodo
          export PATH=/usr/bin:$PATH
      - name: Test setup components
        run: |
          sudo bash mycodo/scripts/upgrade_commands.sh setup-virtualenv
          sudo bash mycodo/scripts/upgrade_commands.sh update-pip3
          sudo bash mycodo/scripts/upgrade_commands.sh update-pip3-packages
          sudo bash mycodo/scripts/upgrade_commands.sh ssl-certs-generate
          sudo bash mycodo/scripts/upgrade_commands.sh compile-translations
          sudo bash mycodo/scripts/upgrade_commands.sh generate-widget-html
          sudo bash mycodo/scripts/generate_translations_pybabel.sh
          printf "\n#### Generating Docs\n"
          env/bin/python mycodo/scripts/generate_manual_actions.py
          env/bin/python mycodo/scripts/generate_manual_functions.py
          env/bin/python mycodo/scripts/generate_manual_inputs_by_measure.py
          env/bin/python mycodo/scripts/generate_manual_inputs.py
          env/bin/python mycodo/scripts/generate_manual_outputs.py
          env/bin/python mycodo/scripts/generate_manual_widgets.py
          printf "\n#### Generating API Manual\n"
          sudo env/bin/python mycodo/start_flask_ui.py &
          sleep 10
          wget --no-check-certificate -p https://127.0.0.1 -O /dev/null
          sudo apt install npm
          sudo npm install -g redoc-cli
          sudo bash mycodo/scripts/generate_manual_api.sh
      - name: Test with pytest
        run: |
          cd mycodo && ../env/bin/pytest -W ignore::DeprecationWarning -s tests/software_tests
